Repository WebTrit/webtrit_dialer, pull requests merged in 2025-03, with the labels that each got.

#19 feat: introduce normalization for dialing phone numbers
  src/components/Settings-Info/Settings.vue
  src/components/Shared/PhoneInput.vue
  src/locales/en.json
  src/locales/es.json
  src/locales/it.json
  src/locales/ru.json
  src/locales/ua.json
  src/store/modules/settings.js
Labels: enhancement

#20 feat: prevent rendering of hidden user balance
  src/components/Shared/UserInfoList.vue
Labels: enhancement

#22 feat: play DTMF tone during in-call dialing
  package-lock.json
  package.json
  src/components/Main/DialogCall/DialogCall.vue
  vue.config.js
Labels: enhancement

#21 fix: render mystery person Gravatar for callee without an email
  src/components/Main/DialogCall/CallInfo.vue
  src/components/Main/DialogCall/DialogCall.vue
  src/components/Shared/Avatar.vue
Labels: bug

#29 feat: release linter rule for linebreak style
  .eslintrc.js
Labels: bug

#26 fix: improve build description and dependencies
  README.md
Labels: bug, documentation

#28 fix: correct type errors in button components
  src/components/Call-History/History.vue
  src/components/Call-History/HistoryList.vue
  src/components/Home-Recent-Calls-Info/CallRecord.vue
  src/components/Shared/DownloadBtn.vue
  src/components/Shared/PlayBtn.vue
Labels: bug

#25 fix: correct inaccurate login error message
  src/mixins.js
Labels: bug

#24 fix: mark "Incoming call declined" as "Missed"
  src/store/modules/call-history.js
Labels: bug

#23 fix: follow the *.wav call-recording extension during download
  src/components/Shared/DownloadBtn.vue
Labels: bug
